[package]
name = "spotify-mini-player"
version = "0.1.0"
description = "Better Mini Player"
authors = ["you"]
edition = "2021"

[lib]
name = "spotify_mini_player_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.8.5", features = [] }
tauri-plugin-opener = "2.0"
tauri-plugin-fs = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "4.0"

